"""Reproducible licensed BodyParts3D bone selection and millimetre mesh packing.
Run from the project root; inputs remain private in assets/archaeology/source.
No soft tissue meshes or compound 'skeleton' group are used.
"""
import csv,re,zipfile,struct,base64,json,hashlib,pathlib
root=pathlib.Path('assets/archaeology');src=root/'source'
rows=list(csv.reader(open(src/'partof_element_parts.txt'),delimiter='\t'));by={}
for r in rows:
 if len(r)>2:by.setdefault(r[0],set()).add(r[2])
pat=r'\b(bone|vertebra|rib|clavicle|scapula|humerus|radius|ulna|femur|tibia|fibula|patella|talus|calcaneus|phalanx|sacrum|coccyx|sternum|mandible|vomer|maxilla|scaphoid|lunate|triquetral|pisiform|trapezium|trapezoid|capitate|hamate|atlas|axis|ethmoid|hyoid|manubrium|xiphoid process)\b'
selected={}
for r in csv.reader(open(src/'partof_parts_list_e.txt'),delimiter='\t'):
 if len(r)>2 and len(by.get(r[0],[]))==1 and re.search(pat,r[2]) and not re.search(r'artery|muscle|disk|cartilage|part of|symphysis|tributary',r[2]):
  selected[next(iter(by[r[0]]))]=(r[0],r[2])
archive=zipfile.ZipFile(src/'bodyparts3d-partof-99.zip');data=[];lo=[1e9]*3;hi=[-1e9]*3
for f,(id,name) in sorted(selected.items()):
 v=[];faces=[]
 for l in archive.read('partof_BP3D_4.0_obj_99/'+f+'.obj').decode().splitlines():
  if l.startswith('v '):
   a=list(map(float,l.split()[1:4]));v.append(a)
   for j in range(3):lo[j]=min(lo[j],a[j]);hi[j]=max(hi[j],a[j])
  elif l.startswith('f '):
   p=[int(t.split('/')[0])-1 for t in l.split()[1:]]
   for j in range(1,len(p)-1):faces.append((p[0],p[j],p[j+1]))
 data.append((f,id,name,v,faces))
scale=1.7/(hi[2]-lo[2]);mid=[(a+b)/2 for a,b in zip(lo,hi)]
positions=[];indices=[];parts=[]
for f,id,name,v,faces in data:
 start=len(positions);grid=.00085 if any(w in name for w in ['bone','mandible','maxilla','vomer','ethmoid']) and max(a[2] for a in v)>1400 else .00165
 keys={};clusters=[];remap=[]
 for a in v:
  p=[(a[0]-mid[0])*scale,(a[2]-mid[2])*scale,-(a[1]-mid[1])*scale]
  k=tuple(round(t/grid) for t in p)
  if k not in keys:keys[k]=len(clusters);clusters.append([*p,1])
  else:
   c=clusters[keys[k]]
   for j in range(3):c[j]+=p[j]
   c[3]+=1
  remap.append(keys[k])
 points=[[a[j]/a[3] for j in range(3)] for a in clusters]
 # Keep global extremities so height remains exactly 1.7.
 for i,a in enumerate(v):
  if a[2]==lo[2] or a[2]==hi[2]:points[remap[i]][1]=(a[2]-mid[2])*scale
 positions.extend(points);first=len(indices)
 seen=set()
 for a,b,c in faces:
  tri=(start+remap[a],start+remap[b],start+remap[c])
  if len(set(tri))<3 or tri in seen:continue
  seen.add(tri);indices.extend(tri)
 parts.append(dict(file=f,concept=id,name=name,indexStart=first,indexCount=len(indices)-first))
q=[round(c/.00005) for p in positions for c in p]
packed=base64.b64encode(struct.pack('<'+'h'*len(q),*q)).decode();ix=base64.b64encode(struct.pack('<'+'I'*len(indices),*indices)).decode()
out="/* BodyParts3D derivative; see assets/archaeology/PROVENANCE.md. Generated by scripts/assets/build-skeleton.py. */\n"
out+="export const BONE_POSITIONS='"+packed+"';\nexport const BONE_INDICES='"+ix+"';\nexport const BONE_PARTS="+json.dumps(parts,separators=(',',':'))+";\n"
pathlib.Path('src/scene/skeleton-data.ts').write_text(out)
manifest=dict(sourceUrl='https://dbarchive.biosciencedbc.jp/data/bodyparts3d/LATEST/partof_BP3D_4.0_obj_99.zip',archiveSha256=hashlib.sha256((src/'bodyparts3d-partof-99.zip').read_bytes()).hexdigest(),generatedSha256=hashlib.sha256(out.encode()).hexdigest(),selectedBones=len(parts),vertices=len(positions),triangles=len(indices)//3,rawBounds=[lo,hi],height=1.7,coordinateChange='raw millimetres X/Y/Z -> metres X/Z/-Y; centred; uniform height 1.7',positionPrecision=.00005,parts=parts)
(root/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps({k:v for k,v in manifest.items() if k not in ['parts']},indent=2))
